name: Update README

on:
  schedule:
            #dias horas minutos segundos microsegundos
    - cron: '0 */12 * * *' # Cada 12 horas 
  workflow_dispatch:

jobs:
  build:
  # construye lo que se le indique en esta mini maquina virtual
    runs-on: ubuntu-latest
    name: Update Profile README
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Update README with recent activity
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
